POST http://localhost:8000/bands/
Content-Type: application/json

{
    "name": "Sparrows of the World",
    "genre": "Electronic",
    "date_formed": "11/7/2025"
}

###
GET http://localhost:8000/bands
