POST http://localhost:8000/bands/
Content-Type: application/json

{
    "name": "Ducks of the World",
    "genre": "Electronic",
    "date_formed": "2025-11-07"
}

###
GET http://localhost:8000/bands
