"""Added date_formed field to Band model

Revision ID: 716cd4487b9f
Revises: edfc9b8e6b80
Create Date: 2025-11-07 20:14:48.512926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '716cd4487b9f'
down_revision: Union[str, Sequence[str], None] = 'edfc9b8e6b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
