"""Added date_formed field to Band model

Revision ID: edfc9b8e6b80
Revises: 95b9445170f1
Create Date: 2025-11-07 19:49:32.890346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'edfc9b8e6b80'
down_revision: Union[str, Sequence[str], None] = '95b9445170f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('band', sa.Column('date_formed', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('band', 'date_formed')
    # ### end Alembic commands ###
